# Pegar al final de /opt/docker-vps/nginx/conf.d/default.conf

# proyecto_5 — API backend Laravel (puerto 8085)
server {
    listen 8085;

    location / {
        proxy_pass http://proyecto_5:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# proyecto_5 — Frontend React (puerto 8086)
server {
    listen 8086;

    location / {
        proxy_pass http://proyecto_5_front:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
